# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

linear_interpolation_cpp <- function(x_r, y, xout_r, rule, verbose) {
    .Call(`_mapprox_linear_interpolation_cpp`, x_r, y, xout_r, rule, verbose)
}

