# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Main function of mapprox() in R
#'
#' \code{mapprox} is an wrapper of \code{linear_interpolation} and
#' \code{linear_interpolation_cpp}.
#'
#' This is the main function of \code{mapprox(..., use_cpp = TRUE)}.
#' Provided data are cleaned beforehand in \code{mapprox} and
#' then passed to this function.
#' \code{x} must be completely gridded data,
#' and duplicated values are not allowed.
#' Also, no NA in \code{x}, \code{y}, and \code{xout} is allowed.
#'
#' @param x Reference data of explanatory variables.
#'   This must be a data frame in which elements are all numeric.
#'   Also, this should be ordered by \code{order} function.
#' @param y Reference data of a target variable.
#'   This must be a numeric vector with length \code{nrow(x)}.
#' @param xout Values of explanatory variables where interpolation is to
#'   take place. This must be a data frame and
#'   \code{ncol(xout)} must be the same as \code{ncol(x)}.
#' @param rule A scalar integer determining how interpolation outside the
#'   given explanatory variables works. This must be eigher
#'   \code{1}, \code{2}, or \code{3}.
#'   If \code{rule = 1}, \code{NA}s are returned for such points.
#'   If \code{rule = 2}, the values at the closest points in the region
#'   given as the reference data are returned.
#'   If \code{rule = 3}, linear extension of the interpolated result is applied.
#' @param verbose Logical. Should progress of the process printed?
#'
#' @return A numeric vector of interpolated result.
#'
#' @seealso [mapprox()]
linear_interpolation_cpp <- function(x_r, y, xout_r, rule, verbose) {
    .Call(`_mapprox_linear_interpolation_cpp`, x_r, y, xout_r, rule, verbose)
}

